### PR TITLE
new tables are added

### PR DESCRIPTION
**Pull request by PrashantAlagawadi**

### CODE REVIEW

**Comment by PrajwalGoudar** [comment]
Remove table todaystasks and instead use sql query to grab the data of todaystask from task table

**Comment by PrajwalGoudar** [comment]
Remove extra spaces and empty lines

**Comment by PrajwalGoudar** [comment]
Remove single quotes from '100' , otherwise it will consider it as string.

**Comment by PrashantAlagawadi** [comment]
but its working correctly

**Comment by PrajwalGoudar** [comment]
https://stackoverflow.com/questions/2078942/should-i-quote-numbers-in-sql

this link will clear your confusion

**Comment by PrajwalGoudar** [comment]
Close #2

**Comment by PrashantAlagawadi** [comment]
Hey,

I just signed the petition "Environmentalists: Stop destruction of 177
hectares of forest land in the Western Ghats" and wanted to see if you
could help by adding your name.

Our goal is to reach 2,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/RyzFL4KKL5

Thanks!
Prashant

**Pull request merged**
